'use client';
import {useEffect,useState} from 'react';
type Item={id:string;name:string;quantity:number;deliveredQuantity:number;returnedQuantity:number};
type Order={id:string;agentId:string|null;status:string;items:Item[]};
export default function Deliveries(){
 const [lookup,setLookup]=useState('');
 const [orders,setOrders]=useState<Order[]>([]);const [id,setId]=useState('');const [items,setItems]=useState<Item[]>([]);const [evidence,setEvidence]=useState('');const [eventKey,setEventKey]=useState('');const [message,setMessage]=useState('');
 const [agentId,setAgentId]=useState('');const [amount,setAmount]=useState('');const [reference,setReference]=useState('');const [payoutKey,setPayoutKey]=useState('');
 const load=(search=lookup)=>fetch(`/api/orders${search?'?id='+encodeURIComponent(search):''}`).then(r=>r.json()).then(d=>{if(d.ok)setOrders(d.orders)});
 useEffect(()=>{load();setEventKey(crypto.randomUUID());setPayoutKey(crypto.randomUUID());},[]);
 async function delivery(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/orders/delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:id,eventKey,evidence,items:items.map(({id,deliveredQuantity,returnedQuantity})=>({id,deliveredQuantity,returnedQuantity}))})});const d=await r.json();setMessage(d.ok?'Entrega registrada. Comisión recalculada.':d.error);if(d.ok){setEventKey(crypto.randomUUID());setEvidence('');await load();}}
 return <main style={{maxWidth:900,margin:'30px auto',padding:24,lineHeight:1.7}}><h1>Entregas verificadas</h1><p>Solo registra cantidades entregadas después de comprobar la prueba del transportista. Las cantidades son acumuladas. Los pedidos deben estar confirmados y reconciliados.</p><form onSubmit={e=>{e.preventDefault();load()}}><label>Buscar cualquier pedido por ID<input value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="ID completo del pedido"/></label><button>Buscar pedido</button></form><p>Sin búsqueda se muestran los últimos 100 pedidos.</p><form onSubmit={delivery}><label>Pedido<select required value={id} onChange={e=>{setId(e.target.value);const o=orders.find(o=>o.id===e.target.value);setItems(o?.items||[]);setAgentId(o?.agentId||'');setEventKey(crypto.randomUUID());}} style={{display:'block',padding:12,width:'100%'}}><option value="">Seleccionar…</option>{orders.map(o=><option key={o.id} value={o.id}>{o.id} · {o.status}</option>)}</select></label>{items.map((item,index)=><div key={item.id} style={{padding:15,borderBottom:'1px solid #ccc'}}><strong>{item.name} · {item.quantity} unidades pedidas</strong><div><label>Entregadas <input type="number" min={item.deliveredQuantity} max={item.quantity} required value={item.deliveredQuantity} onChange={e=>setItems(items.map((i,n)=>n===index?{...i,deliveredQuantity:Number(e.target.value)}:i))}/></label> <label>Devueltas <input type="number" min={item.returnedQuantity} max={item.deliveredQuantity} required value={item.returnedQuantity} onChange={e=>setItems(items.map((i,n)=>n===index?{...i,returnedQuantity:Number(e.target.value)}:i))}/></label></div></div>)}<label>Referencia y evidencia de entrega<textarea required minLength={10} maxLength={1000} value={evidence} onChange={e=>setEvidence(e.target.value)} style={{display:'block',border:'1px solid',width:'100%',padding:12}}/></label><button style={{padding:15,marginTop:12}}>Registrar entrega verificada</button></form><p role="status">{message}</p><hr/><h2>Registrar comisión pagada</h2><p>Registra una transferencia realizada fuera de la plataforma. Este formulario no mueve dinero y rechaza importes superiores al saldo respaldado por entregas.</p><form onSubmit={async e=>{e.preventDefault();const r=await fetch('/api/admin/payouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agentId,amount:Number(amount),reference,payoutKey})});const d=await r.json();setMessage(d.ok?'Pago registrado.':d.error);if(d.ok){setPayoutKey(crypto.randomUUID());setAmount('');setReference('')}}}><label>ID afiliado<input required value={agentId} onChange={e=>setAgentId(e.target.value)}/></label><label>Importe EUR<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Referencia de transferencia<input required minLength={5} value={reference} onChange={e=>setReference(e.target.value)}/></label><button style={{padding:15}}>Registrar pago</button></form></main>
}
